name: 🐛 Bug Report
description: Create a report to help us improve the repository.
title: "[Bug]: "
labels: "type: bug"
body:
- type: textarea
  attributes:
    label: Describe the bug
    placeholder: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggested improvements or fixes
    placeholder: "A clear and concise description of what you want to happen."
  validations:
    required: false
- type: input
  attributes:
    label: Related issue(s)/PR(s)
    placeholder: "Let us know if this is related to any issue/pull request."
  validations:
    required: false
